### ISSUE TITLE
window is very small and therefore the image that makes the choice of bounding boxes very difficult

### ISSUE THREAD

**Issue by fraten** [errolPereira/Semi-Automatic-Image-Annotation-Tool#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by errolPereira** [comment]
Hi,
Can you please give details on the machine and environment you are using. 
OS : 
python version:
conda version:

Thanks.

**Comment by u1353279** [comment]
Thank you for this program.
We are looking at a startup in the UK for which we would want to be able to automate the annotation  of images.
I'd like to discuss more if you are open to collaboration.
Please leave your email to discuss.

**Comment by errolPereira** [comment]
@u1353279 Please find below my email address 
errolpereira06@gmail.com

**Comment by errolPereira** [comment]
Closing the issue as there was no reply
